import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, toast } from 'react-toastify';

import { ApolloWrapper } from "./apollo/wrapper";
import StoreProvider from "./redux/provider";
import SessionProviders from "./nextauth/session";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "G-SNEAKER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <StoreProvider>
          <SessionProviders>
          <ApolloWrapper>
            <ToastContainer position="bottom-right"/>
              {children}
          </ApolloWrapper>
          </SessionProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
